s/V23_ROOT/JIRI_ROOT/g
Change-Id: Ibf31c00f97d58a448460a8137cd451baf2d0235d

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -23,24 +23,24 @@ run() {
 }
 
 check_environment() {
-  # Check that the V23_ROOT environment variable is set.
-  if [[ -z "${V23_ROOT}" ]]; then
-    echo "The V23_ROOT environment variable is not set."
+  # Check that the JIRI_ROOT environment variable is set.
+  if [[ -z "${JIRI_ROOT}" ]]; then
+    echo "The JIRI_ROOT environment variable is not set."
     echo "Set the environment variable and re-run."
     exit 1
   fi
 
-  # Check that the V23_ROOT environment variable does not contain space.
+  # Check that the JIRI_ROOT environment variable does not contain space.
   local -r PATTERN="[ ']"
-  if [[ "${V23_ROOT}" =~ "${PATTERN}" ]]; then
-    echo "The V23_ROOT environment variable cannot contain space."
+  if [[ "${JIRI_ROOT}" =~ "${PATTERN}" ]]; then
+    echo "The JIRI_ROOT environment variable cannot contain space."
     echo "NOTE: This limitation is inherited from Autotools."
     exit 1
   fi
 
-  # Check that the V23_ROOT path does not exist.
-  if [[ -e "${V23_ROOT}" ]]; then
-    echo "The ${V23_ROOT} path already exists."
+  # Check that the JIRI_ROOT path does not exist.
+  if [[ -e "${JIRI_ROOT}" ]]; then
+    echo "The ${JIRI_ROOT} path already exists."
     echo "Remove it or choose a different path and re-run."
     exit 1
   fi
@@ -100,24 +100,24 @@ check_environment() {
 main() {
   check_environment
 
-  trap "rm -rf ${V23_ROOT}" INT TERM EXIT
+  trap "rm -rf ${JIRI_ROOT}" INT TERM EXIT
 
   # Create initial directories.
-  run mkdir -p "${V23_ROOT}/devtools/bin"
+  run mkdir -p "${JIRI_ROOT}/devtools/bin"
 
   # Clone the manifest repository.
-  run git clone https://fuchsia.googlesource.com/fnl-start "${V23_ROOT}/.manifest"
+  run git clone https://fuchsia.googlesource.com/fnl-start "${JIRI_ROOT}/.manifest"
 
   # Get and install the jiri tool.
-  GOPATH="${V23_ROOT}/tmp" run go get -d v.io/jiri
-  GOPATH="${V23_ROOT}/tmp" run go build -o "${V23_ROOT}/devtools/bin/jiri" v.io/jiri
-  rm -rf "${V23_ROOT}/tmp"
+  GOPATH="${JIRI_ROOT}/tmp" run go get -d v.io/jiri
+  GOPATH="${JIRI_ROOT}/tmp" run go build -o "${JIRI_ROOT}/devtools/bin/jiri" v.io/jiri
+  rm -rf "${JIRI_ROOT}/tmp"
 
   # Install all vanadium repositories and tools.
   local -r NATTEMPTS=3
   local -r VANADIUM_MANIFEST=minimal
   for attempt in $(seq 1 "${NATTEMPTS}"); do
-    "${V23_ROOT}/devtools/bin/jiri" update -manifest="${VANADIUM_MANIFEST}" && break
+    "${JIRI_ROOT}/devtools/bin/jiri" update -manifest="${VANADIUM_MANIFEST}" && break
     if [[ "${attempt}" == "${NATTEMPTS}" ]]; then
       echo "\"jiri update\" failed ${NATTEMPTS} times in a row."
       echo "This can happen when our repository servers are"
@@ -127,7 +127,7 @@ main() {
     echo "\"jiri update\" failed, trying again."
   done
 
-  echo "Please add ${V23_ROOT}/devtools/bin to your PATH."
+  echo "Please add ${JIRI_ROOT}/devtools/bin to your PATH."
 
   trap - EXIT
 }
